"""Re-verify every vector in fixtures/canonical-vectors.json.

The fixture file is generated by `fixtures/generate.py` against this very
canonical_json implementation, so passing here means we still produce the
same bytes. The companion vitest at `extension/test/vectors.test.ts`
reads the *same* file — if both sides keep passing, JS and Python remain
bit-for-bit compatible.

If you change `protocol.py` and a vector here goes red, you've changed the
wire format. Run `python3 fixtures/generate.py` to regenerate AFTER you've
updated the matching TS code and bumped the protocol version.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
from pathlib import Path

import pytest

from sallyport_daemon.protocol import canonical_json

VECTORS_PATH = Path(__file__).resolve().parents[2] / "fixtures" / "canonical-vectors.json"
SECRET = bytes(32)


def _load() -> list[dict[str, object]]:
    res: list[dict[str, object]] = json.loads(VECTORS_PATH.read_text(encoding="utf-8"))
    return res


@pytest.mark.parametrize("vec", _load(), ids=lambda v: v["name"])
def test_canonical_matches_fixture(vec: dict[str, object]) -> None:
    """Our canonical_json must produce exactly the canonical string the
    fixture pinned. If this fails, we've drifted — update both sides
    intentionally or revert."""
    assert canonical_json(vec["input"]) == vec["canonical"]


@pytest.mark.parametrize("vec", _load(), ids=lambda v: v["name"])
def test_hmac_matches_fixture(vec: dict[str, object]) -> None:
    """HMAC-SHA256 over the canonical bytes must equal the fixture's MAC.

    This covers the full wire-format invariant: canonical bytes are the
    same AND the MAC bytes are the same. Either side drifting in either
    direction (e.g. wrong UTF-8 handling, different HMAC key encoding)
    will trip this."""
    canonical = vec["canonical"]
    assert isinstance(canonical, str)
    mac_bytes = hmac.new(SECRET, canonical.encode("utf-8"), hashlib.sha256).digest()
    assert base64.b64encode(mac_bytes).decode("ascii") == vec["mac_b64"]


def test_fixture_file_has_no_duplicate_names() -> None:
    """Catch accidental copy-paste in the generator."""
    names = [v["name"] for v in _load()]
    assert len(names) == len(set(names)), f"duplicate vector names: {names}"


def test_fixture_file_is_non_empty() -> None:
    assert len(_load()) >= 10  # we always carry at least a baseline set
